name: Terraform Build

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: bq-training-assignment-terraform

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::522814707398:role/role-for-github-workflow
        aws-region: us-east-1

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Terraform plan to see what changes are pending
    - name: Terraform Plan
      run: terraform plan

    # Validate the Terraform plan (ensure to confirm apply if it's in production)
    - name: Terraform Validate
      run: terraform validate
