name: Terraform Apply

on:
  workflow_dispatch:  # Manual trigger from GitHub UI for approval
    inputs:
      approval:
        description: 'Type "yes" to apply changes'
        required: true
        default: 'no'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    # Check if the first workflow has completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::522814707398:role/role-for-github-workflow
          aws-region: us-east-1

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Wait for manual approval from the user
      - name: Wait for manual approval
        id: approval
        run: |
          if [[ "${{ github.event.inputs.approval }}" != "yes" ]]; then
            echo "Approval input was not 'yes'. Exiting the workflow."
            exit 1
          else
            echo "Approval received. Proceeding with Terraform apply."
          fi

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Apply the Terraform plan to create the infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve
