name: Terraform Apply

on:
  workflow_dispatch: # Requires manual approval
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        default: "production"
      apply_terraform:
        description: "Run terraform apply?"
        required: true
        type: boolean

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    environment: ${{ inputs.environment }} # Dynamically select environment

    defaults:
      run:
        working-directory: bq-training-assignment-terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::522814707398:role/role-for-github-workflow
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      if: ${{ inputs.apply_terraform }} # Correct boolean check
      run: terraform apply -auto-approve
