repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0 # Replace this with the latest valid version
    hooks:
      - id: terraform_fmt
        files: \.tf$
      # - id: terraform_validate
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-exiting-file=true # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true
